version: "3.8"

services:
  web:
    depends_on:
      - api
    build: ./todolist-react
    image: todolist_web:1
    ports:
      - "80:80"
    restart: unless-stopped

  api:
    depends_on:
      - db
      - rmq
    links:
      - db
      - rmq
    build: ./todolist-spring
    image: todolist_api:1
    ports: 
      - "9090:9090"
    environment: 
      DB_URL: mongodb://db:27020/todolist
      RMQ_HOST: rmq
    restart: unless-stopped

  db:
    image: mongo:4.0-xenial
    command: mongod --port 27020
    ports:
      - "27020:27020"
    volumes:
      - todolist:/data/db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:27020"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  rmq:
    image: rabbitmq:3.9.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - todolist:/rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5672"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
    restart: unless-stopped


volumes:
  todolist:
