version: "3.8"

services:
  web:
    depends_on:
      - api
    build: ./todolist-react
    image: todolist_web:1
    ports:
      - "80:80"
    restart: unless-stopped

  api:
    depends_on:
      - db
    build: ./todolist-spring
    image: todolist_api:1
    ports: 
      - "9090:9090"
    environment: 
      DB_URL: mongodb://db:27020/todolist
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost:27020" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  db:
    image: mongo:4.0-xenial
    command: mongod --port 27020
    ports:
      - "27020:27020"
    volumes:
      - todolist:/data/db
    restart: unless-stopped

volumes:
  todolist:
